# Generated by Django 4.1.1 on 2022-10-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profilepost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepost',
            name='pub_date',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
    ]
