# Generated by Django 4.1.1 on 2022-10-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userfriends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfriends',
            old_name='user2',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='userfriends',
            old_name='user1',
            new_name='owner',
        ),
    ]
