# Generated by Django 4.1.1 on 2022-10-01 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userfriends_friend_alter_userfriends_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfriends',
            name='user_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to=settings.AUTH_USER_MODEL),
        ),
    ]
